# Generated by Django 5.2.15 on 2026-06-21 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cultura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_comum', models.CharField(max_length=100)),
                ('nome_cientifico', models.CharField(blank=True, max_length=150)),
                ('dias_colheita', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('hortaliça', 'Hortaliça'), ('fruto', 'Fruto'), ('raiz', 'Raiz'), ('legume', 'Legume'), ('cereal', 'Cereal')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CalendarioPlantio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regiao', models.CharField(choices=[('norte', 'Norte'), ('nordeste', 'Nordeste'), ('centro-oeste', 'Centro-Oeste'), ('sudeste', 'Sudeste'), ('sul', 'Sul')], max_length=50)),
                ('mes_inicio', models.PositiveSmallIntegerField()),
                ('mes_fim', models.PositiveSmallIntegerField()),
                ('cultura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendarios', to='culturas.cultura')),
            ],
        ),
        migrations.CreateModel(
            name='ExigenciaClimatica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_minima', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temp_maxima', models.DecimalField(decimal_places=2, max_digits=5)),
                ('umidade_minima', models.PositiveSmallIntegerField()),
                ('umidade_maxima', models.PositiveSmallIntegerField()),
                ('chuva_minima_mm', models.DecimalField(decimal_places=2, max_digits=6)),
                ('chuva_maxima_mm', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cultura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exigencia_climatica', to='culturas.cultura')),
            ],
        ),
        migrations.CreateModel(
            name='FaseLunarIdeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase_lua', models.CharField(choices=[('nova', 'Nova'), ('crescente', 'Crescente'), ('cheia', 'Cheia'), ('minguante', 'Minguante')], max_length=20)),
                ('cultura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fases_lunares', to='culturas.cultura')),
            ],
        ),
    ]
